### ISSUE TITLE
Connection error while accessing Dimensions Analytics API on remote

### ISSUE THREAD

**Issue by saralafia** [digital-science/dimcli#73]
I am accessing the Dimensions API with dimcli on my university's remote HPC environment. My credentials are not recognized. I have tried both manual login and using the [authentication](https://digital-science.github.io/dimcli/getting-started.html#authentication) helper. How can I overcome this connection error? The error I get is:

Login failed: please ensure your credentials are correct.
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.8-anaconda/2020.07/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/sw/arcts/centos7/python3.8-anaconda/2020.07/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/sw/arcts/centos7/python3.8-anaconda/2020.07/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by lambdamusic** [comment]
Please email supportapi@dimensions.ai for this sort of issues
